BEGIN;

DELETE FROM TRAVEL;
DELETE FROM TOPUP;
DELETE FROM REPLACEMENT;
DELETE FROM REPLACEMENTORDER;
DELETE FROM CARD;
DELETE FROM DOCK;

DELETE FROM SCOOTER;
DELETE FROM CLIENT;
DELETE FROM EMPLOYEE;

DELETE FROM SCOOTERMODEL;
DELETE FROM STATION;
DELETE FROM TYPEOF;
DELETE FROM PERSON;
DELETE FROM SERVICECOST;

COMMIT;
